name: my_garage
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  # For generating model
  freezed_annotation: ^1.1.0
  # For persisting data
  uuid: ^3.0.5
  shared_preferences: ^2.0.13
  rxdart: ^0.27.3
  # For form validation
  formz: ^0.4.1
  # For picking and saving images
  image_picker: ^0.8.4+9
  path_provider: ^2.0.9
  # For setting up launcher icon
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # For generating model
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/auto.jpg
    - assets/images/no_image_available.png
    - assets/images/drive_type.png
    - assets/images/fuel.png
    - assets/images/kms_driven.png
    - assets/images/transmission.png
    - assets/images/year.png
